In [1]:
import numpy as np
from random import*

In [10]:
A9=np.matrix([[0, 0, 0, 0, 0.5, 0], 
              [0.5, 0.5, 0.5, 0.5, 0.5, 1], 
              [0.5, 0, 0, 0, 0, 0], 
              [0, 0.5, 0, 0, 0, 0], 
              [0, 0, 0.5, 0, 0, 0], 
              [0, 0, 0, 0.5, 0, 0]])

A9T=np.transpose(A9)

vt9=np.matrix([0, 1, 0, 0, 0, 0])

v9=np.transpose(vt9)

A10=np.matrix([[1/6, 1/6, 1/6, 1/6, 1/6, 1/6], 
               [1/6, 1/6, 1/6, 1/6, 1/6, 1/6], 
               [1/6, 1/6, 1/6, 1/6, 1/6, 1/6], 
               [1/6, 1/6, 1/6, 1/6, 1/6, 1/6], 
               [1/6, 1/6, 1/6, 1/6, 1/6, 1/6], 
               [1/6, 1/6, 1/6, 1/6, 1/6, 1/6]])
vt10=np.matrix([1, 0, 0, 0, 0, 0])
v10=np.transpose(vt10)

A=A9*A10


In [11]:
A9*v9

matrix([[0. ],
        [0.5],
        [0. ],
        [0.5],
        [0. ],
        [0. ]])

In [7]:
np.linalg.eig(A9)

(array([-0.25+0.4330127j, -0.25-0.4330127j,  1.  +0.j       ,
         0.5 +0.j       , -0.25+0.4330127j, -0.25-0.4330127j]),
 matrix([[-2.70030862e-01+0.46770717j, -2.70030862e-01-0.46770717j,
          -1.84729725e-16+0.j        ,  4.08248290e-01+0.j        ,
          -2.32600386e-01-0.17938884j, -2.32600386e-01+0.17938884j],
         [ 1.54303350e-01-0.13363062j,  1.54303350e-01+0.13363062j,
          -8.72871561e-01+0.j        , -4.08248290e-01+0.j        ,
           2.48520641e-01-0.43045038j,  2.48520641e-01+0.43045038j],
         [ 5.40061725e-01+0.j        ,  5.40061725e-01-0.j        ,
           1.64204200e-16+0.j        ,  4.08248290e-01+0.j        ,
          -3.90551023e-02+0.29113226j, -3.90551023e-02-0.29113226j],
         [-1.92879187e-01-0.06681531j, -1.92879187e-01+0.06681531j,
          -4.36435780e-01+0.j        , -4.08248290e-01+0.j        ,
          -4.97041283e-01+0.j        , -4.97041283e-01-0.j        ],
         [-2.70030862e-01-0.46770717j, -2.70030862e-01

In [4]:
np.sum(A,axis=0)

matrix([[1., 1., 1., 1., 1., 1.]])

In [5]:
np.linalg.inv([[0.6, 0.2],[0.4, 0.8]])

array([[ 2. , -0.5],
       [-1. ,  1.5]])

In [6]:
np.add(1.0, 4.0)


5.0

In [10]:
x1 = np.arange(9.0).reshape((3, 3))
print(x1)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [9]:
x2 = np.arange(9.0).reshape((3,3))
x2t = np.transpose(x2)
print(x2t)

[[0. 3. 6.]
 [1. 4. 7.]
 [2. 5. 8.]]


In [13]:
np.add(x1, x2t)

array([[ 0.,  4.,  8.],
       [ 4.,  8., 12.],
       [ 8., 12., 16.]])

In [14]:
np.multiply(x1,x2t)

array([[ 0.,  3., 12.],
       [ 3., 16., 35.],
       [12., 35., 64.]])

In [22]:
T=np.matrix([[1/4, 3/4, 1/2], 
              [1/2, 0, 1/2], 
              [1/4, 1/4, 0]])

R=np.matrix([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

In [27]:
W=np.multiply(T,R)
W

matrix([[0.25, 1.5 , 1.5 ],
        [2.  , 0.  , 3.  ],
        [1.75, 2.  , 0.  ]])

In [35]:
v0=np.matrix([[1/2], 
              [1/2], 
              [0]])

In [36]:
W*v0

matrix([[0.875],
        [1.   ],
        [1.875]])

In [3]:
def Reward_Matrix(n):
    RewardMatrix=np.zeros((n,n))
    for ii in range(n):
            for jj in range(n):
                RewardMatrix[ii,jj]=normalvariate(30.0,10.0)
    return RewardMatrix

In [23]:
N = 100
T = Reward_Matrix(N)
type(T)

numpy.ndarray

In [55]:
L=int(N/10)

K=np.zeros((L,L))
F=np.zeros((L,L))

K[0,0]=np.sum(T[0:10,0:10])
K[0,1]=np.sum(T[0:10,10:20])
K[0,2]=np.sum(T[0:10,20:30])
K[0,3]=np.sum(T[0:10,30:40])
K[0,4]=np.sum(T[0:10,40:50])
K[0,5]=np.sum(T[0:10,50:60])
K[0,6]=np.sum(T[0:10,60:70])
K[0,7]=np.sum(T[0:10,70:80])
K[0,8]=np.sum(T[0:10,80:90])
K[0,9]=np.sum(T[0:10,90:100])

K[1,0]=np.sum(T[10:20,0:10])
K[1,1]=np.sum(T[10:20,10:20])
K[1,2]=np.sum(T[10:20,20:30])
K[1,3]=np.sum(T[10:20,30:40])
K[1,4]=np.sum(T[10:20,40:50])
K[1,5]=np.sum(T[10:20,50:60])
K[1,6]=np.sum(T[10:20,60:70])
K[1,7]=np.sum(T[10:20,70:80])
K[1,8]=np.sum(T[10:20,80:90])
K[1,9]=np.sum(T[10:20,90:100])

for nn in range(L):
    for mm in range(L):
        F[nn,mm]=np.sum(T[(nn*L):((nn*L)+L),(mm*L):((mm*L)+L)])

print(K)
print(F)

[[2933.54458177 2885.17212755 3077.20738533 3152.31941372 2974.84809815
  2953.52945268 3122.80337403 3067.76571523 3133.92235446 2879.14315043]
 [3024.24867357 3106.58137818 2898.78199824 3036.76683064 3116.26998681
  3232.6581888  2933.02567832 3113.43866714 3024.17089821 2954.92086236]
 [   0.            0.            0.            0.            0.
     0.            0.            0.            0.            0.        ]
 [   0.            0.            0.            0.            0.
     0.            0.            0.            0.            0.        ]
 [   0.            0.            0.            0.            0.
     0.            0.            0.            0.            0.        ]
 [   0.            0.            0.            0.            0.
     0.            0.            0.            0.            0.        ]
 [   0.            0.            0.            0.            0.
     0.            0.            0.            0.            0.        ]
 [   0.            0.    

In [46]:
A10=np.matrix([[1/6, 1/6, 1/6, 1/6, 1/6], 
               [1/6, 1/6, 1/6, 1/6, 1/6], 
               [1/6, 1/6, 1/6, 1/6, 1/6], 
               [1/6, 1/6, 1/6, 1/6, 1/6], 
               [1/6, 1/6, 1/6, 1/6, 1/6], 
               [1/6, 1/6, 1/6, 1/6, 1/6]])

In [50]:
np.shape(A10)[0]

6

In [53]:
AAAA=[]
for ii in range ( np.shape(A10)[0] ):
    AAAA.append(np.sum(A10[ii,:]))
    
AAAA

[0.8333333333333333,
 0.8333333333333333,
 0.8333333333333333,
 0.8333333333333333,
 0.8333333333333333,
 0.8333333333333333]