In [1]:
import numpy as np
import pandas as pd
from random import*
import mdptoolbox
import time

In [ ]:
def Mean_Matrix():
    
    

In [2]:
def Mean_Matrix1(case,n):
    
    if case=="real":
        #Importing the origin destination matrices as ODi (i=1,2,3,...)
        OD1 = pd.read_csv('Demand_Jun_04_2011.csv', header=None)
        OD2 = pd.read_csv('Demand_Jun_05_2011.csv', header=None)
        OD3 = pd.read_csv('Demand_Jun_06_2011.csv', header=None)
        
        #This creates a numpy matrix with the values of the pandas matrices above.
        OD1ValuesRaw = OD1.values
        OD2ValuesRaw = OD2.values
        OD3ValuesRaw = OD3.values
        
        #This deletes the row and column headers
        OD1Values = np.delete(OD1ValuesRaw,0,1)
        OD1Values = np.delete(OD1Values,0,0)
        OD2Values = np.delete(OD2ValuesRaw,0,1)
        OD2Values = np.delete(OD2Values,0,0)
        OD3Values = np.delete(OD3ValuesRaw,0,1)
        OD3Values = np.delete(OD3Values,0,0)
        
        #This adds up the values of the specific day-time OD matrices.
        sum1=np.add(OD1Values, OD2Values)
        PreMeanMatrix1_Int=np.add(sum1, OD3Values)
        
        #This changes the type of the values of the OD matrix.
        PreMeanMatrix1_Float=PreMeanMatrix1_Int.astype(float)

        #This creates a Mean Matrix. This divides the Pre-Mean Matrix by N, the number of original matrices.
        N_1 = 3
        MeanMatrix1_Float=(1/N_1)*PreMeanMatrix1_Float

        #Creating a copy of the previous matrix, a list of the sum of the row elements.
        PreTransitionMatrix1=MeanMatrix1_Float.copy()
             
        MeanMatrix1=np.asmatrix(MeanMatrix1_Float.copy())

        return MeanMatrix1
    
    else:
        pass

In [3]:
def Mean_Matrix2(case,n):
    
    if case=="real":
        #Importing the origin destination matrices as ODi (i=1,2,3,...)        
        OD4 = pd.read_csv('Demand_Jun_07_2011.csv', header=None)
        OD5 = pd.read_csv('Demand_Jun_08_2011.csv', header=None)
        
        #This creates a numpy matrix with the values of the pandas matrices above.        
        OD4ValuesRaw = OD4.values
        OD5ValuesRaw = OD5.values
        
        #This deletes the row and column headers
        OD4Values = np.delete(OD4ValuesRaw,0,1)
        OD4Values = np.delete(OD4Values,0,0)
        OD5Values = np.delete(OD5ValuesRaw,0,1)
        OD5Values = np.delete(OD5Values,0,0)
        
        #This adds up the values of the specific day-time OD matrices.
        PreMeanMatrix2_Int=np.add(OD4Values, OD5Values)
        
        #This changes the type of the values of the OD matrix.
        PreMeanMatrix2_Float=PreMeanMatrix2_Int.astype(float)
        
        #This creates a Mean Matrix. This divides the Pre-Mean Matrix by N, the number of original matrices.
        N_2 = 2
        MeanMatrix2_Float=(1/N_2)*PreMeanMatrix2_Float
        
        #Creating a copy of the previous matrix, a list of the sum of the row elements.
        PreTransitionMatrix2=MeanMatrix2_Float.copy()
        
        MeanMatrix2=np.asmatrix(MeanMatrix2_Float.copy())
        
        return MeanMatrix2
    
    else:
        pass

In [4]:
ti=time.time()
MM1 = Mean_Matrix1("real", 8300)
print(time.time()-ti)

/home/santiagortiz/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2901: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):


76.60527563095093


In [5]:
ti=time.time()
MM2 = Mean_Matrix2("real", 8300)
print(time.time()-ti)

/home/santiagortiz/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2901: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):


36.710004806518555


In [6]:
print(MM1)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [7]:
print(MM2)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [3]:
NewMM1 = np.empty((10,10), dtype=int)
NewMM2 = np.empty((10,10), dtype=int)
l = 830

ti=time.time()
suma00 = 0.0
for ii in range(0, l):
    for jj in range(0, l):
        suma00 = suma00 + MM[ii,jj]
    for jj in range()

for ii in range(l, 2*l):
    for jj in range(l, 2*l)

print(time.time()-ti)

In [16]:
TT=np.array([[0.5   , 0.    , 0.5   ],
              [0.0625, 0.875 , 0.0625],
              [0.    , 0.    , 1.    ]]
            )

TTB = TT[0:3,0:2]

TTB


#suma = 0.0

#for ii in range(0,2):
#    for jj in range(0,2):
#        suma = suma + TT[ii,jj]
#print(suma)
#print(0.5 + 0.0625 + 0.875)
#NewTT = np.empty((10,10), dtype=int)
#NewTT[0,0] = np.sum(TT[0:2,0:2])
#print(NewTT)

array([[0.5   , 0.    ],
       [0.0625, 0.875 ],
       [0.    , 0.    ]])

In [9]:
#because it wouldn't work with nested loops.

NewMM1[0,0] = np.sum(MM1[0*l:1*l, 0:(0+1)*l])
NewMM1[1,0] = np.sum(MM1[1*l:2*l, 0:(0+1)*l])
NewMM1[2,0] = np.sum(MM1[2*l:3*l, 0:(0+1)*l])
NewMM1[3,0] = np.sum(MM1[3*l:4*l, 0:(0+1)*l])
NewMM1[4,0] = np.sum(MM1[4*l:5*l, 0:(0+1)*l])
NewMM1[5,0] = np.sum(MM1[5*l:6*l, 0:(0+1)*l])
NewMM1[6,0] = np.sum(MM1[6*l:7*l, 0:(0+1)*l])
NewMM1[7,0] = np.sum(MM1[7*l:8*l, 0:(0+1)*l])
NewMM1[8,0] = np.sum(MM1[8*l:9*l, 0:(0+1)*l])
NewMM1[9,0] = np.sum(MM1[9*l:10*l, 0:(0+1)*l])    
NewMM1[0,1] = np.sum(MM1[0*l:1*l, 1*l:(1+1)*l])
NewMM1[1,1] = np.sum(MM1[1*l:2*l, 1*l:(1+1)*l])
NewMM1[2,1] = np.sum(MM1[2*l:3*l, 1*l:(1+1)*l])
NewMM1[3,1] = np.sum(MM1[3*l:4*l, 1*l:(1+1)*l])
NewMM1[4,1] = np.sum(MM1[4*l:5*l, 1*l:(1+1)*l])
NewMM1[5,1] = np.sum(MM1[5*l:6*l, 1*l:(1+1)*l])
NewMM1[6,1] = np.sum(MM1[6*l:7*l, 1*l:(1+1)*l])
NewMM1[7,1] = np.sum(MM1[7*l:8*l, 1*l:(1+1)*l])
NewMM1[8,1] = np.sum(MM1[8*l:9*l, 1*l:(1+1)*l])
NewMM1[9,1] = np.sum(MM1[9*l:10*l, 1*l:(1+1)*l])
NewMM1[0,2] = np.sum(MM1[0*l:1*l, 2*l:(2+1)*l])
NewMM1[1,2] = np.sum(MM1[1*l:2*l, 2*l:(2+1)*l])
NewMM1[2,2] = np.sum(MM1[2*l:3*l, 2*l:(2+1)*l])
NewMM1[3,2] = np.sum(MM1[3*l:4*l, 2*l:(2+1)*l])
NewMM1[4,2] = np.sum(MM1[4*l:5*l, 2*l:(2+1)*l])
NewMM1[5,2] = np.sum(MM1[5*l:6*l, 2*l:(2+1)*l])
NewMM1[6,2] = np.sum(MM1[6*l:7*l, 2*l:(2+1)*l])
NewMM1[7,2] = np.sum(MM1[7*l:8*l, 2*l:(2+1)*l])
NewMM1[8,2] = np.sum(MM1[8*l:9*l, 2*l:(2+1)*l])
NewMM1[9,2] = np.sum(MM1[9*l:10*l, 2*l:(2+1)*l])
NewMM1[0,3] = np.sum(MM1[0*l:1*l, 3*l:(3+1)*l])
NewMM1[1,3] = np.sum(MM1[1*l:2*l, 3*l:(3+1)*l])
NewMM1[2,3] = np.sum(MM1[2*l:3*l, 3*l:(3+1)*l])
NewMM1[3,3] = np.sum(MM1[3*l:4*l, 3*l:(3+1)*l])
NewMM1[4,3] = np.sum(MM1[4*l:5*l, 3*l:(3+1)*l])
NewMM1[5,3] = np.sum(MM1[5*l:6*l, 3*l:(3+1)*l])
NewMM1[6,3] = np.sum(MM1[6*l:7*l, 3*l:(3+1)*l])
NewMM1[7,3] = np.sum(MM1[7*l:8*l, 3*l:(3+1)*l])
NewMM1[8,3] = np.sum(MM1[8*l:9*l, 3*l:(3+1)*l])
NewMM1[9,3] = np.sum(MM1[9*l:10*l, 3*l:(3+1)*l])
NewMM1[0,4] = np.sum(MM1[0*l:1*l, 4*l:(4+1)*l])
NewMM1[1,4] = np.sum(MM1[1*l:2*l, 4*l:(4+1)*l])
NewMM1[2,4] = np.sum(MM1[2*l:3*l, 4*l:(4+1)*l])
NewMM1[3,4] = np.sum(MM1[3*l:4*l, 4*l:(4+1)*l])
NewMM1[4,4] = np.sum(MM1[4*l:5*l, 4*l:(4+1)*l])
NewMM1[5,4] = np.sum(MM1[5*l:6*l, 4*l:(4+1)*l])
NewMM1[6,4] = np.sum(MM1[6*l:7*l, 4*l:(4+1)*l])
NewMM1[7,4] = np.sum(MM1[7*l:8*l, 4*l:(4+1)*l])
NewMM1[8,4] = np.sum(MM1[8*l:9*l, 4*l:(4+1)*l])
NewMM1[9,4] = np.sum(MM1[9*l:10*l, 4*l:(4+1)*l])
NewMM1[0,5] = np.sum(MM1[0*l:1*l, 5*l:(5+1)*l])
NewMM1[1,5] = np.sum(MM1[1*l:2*l, 5*l:(5+1)*l])
NewMM1[2,5] = np.sum(MM1[2*l:3*l, 5*l:(5+1)*l])
NewMM1[3,5] = np.sum(MM1[3*l:4*l, 5*l:(5+1)*l])
NewMM1[4,5] = np.sum(MM1[4*l:5*l, 5*l:(5+1)*l])
NewMM1[5,5] = np.sum(MM1[5*l:6*l, 5*l:(5+1)*l])
NewMM1[6,5] = np.sum(MM1[6*l:7*l, 5*l:(5+1)*l])
NewMM1[7,5] = np.sum(MM1[7*l:8*l, 5*l:(5+1)*l])
NewMM1[8,5] = np.sum(MM1[8*l:9*l, 5*l:(5+1)*l])
NewMM1[9,5] = np.sum(MM1[9*l:10*l, 5*l:(5+1)*l])
NewMM1[0,6] = np.sum(MM1[0*l:1*l, 6*l:(6+1)*l])
NewMM1[1,6] = np.sum(MM1[1*l:2*l, 6*l:(6+1)*l])
NewMM1[2,6] = np.sum(MM1[2*l:3*l, 6*l:(6+1)*l])
NewMM1[3,6] = np.sum(MM1[3*l:4*l, 6*l:(6+1)*l])
NewMM1[4,6] = np.sum(MM1[4*l:5*l, 6*l:(6+1)*l])
NewMM1[5,6] = np.sum(MM1[5*l:6*l, 6*l:(6+1)*l])
NewMM1[6,6] = np.sum(MM1[6*l:7*l, 6*l:(6+1)*l])
NewMM1[7,6] = np.sum(MM1[7*l:8*l, 6*l:(6+1)*l])
NewMM1[8,6] = np.sum(MM1[8*l:9*l, 6*l:(6+1)*l])
NewMM1[9,6] = np.sum(MM1[9*l:10*l, 6*l:(6+1)*l])
NewMM1[0,7] = np.sum(MM1[0*l:1*l, 7*l:(7+1)*l])
NewMM1[1,7] = np.sum(MM1[1*l:2*l, 7*l:(7+1)*l])
NewMM1[2,7] = np.sum(MM1[2*l:3*l, 7*l:(7+1)*l])
NewMM1[3,7] = np.sum(MM1[3*l:4*l, 7*l:(7+1)*l])
NewMM1[4,7] = np.sum(MM1[4*l:5*l, 7*l:(7+1)*l])
NewMM1[5,7] = np.sum(MM1[5*l:6*l, 7*l:(7+1)*l])
NewMM1[6,7] = np.sum(MM1[6*l:7*l, 7*l:(7+1)*l])
NewMM1[7,7] = np.sum(MM1[7*l:8*l, 7*l:(7+1)*l])
NewMM1[8,7] = np.sum(MM1[8*l:9*l, 7*l:(7+1)*l])
NewMM1[9,7] = np.sum(MM1[9*l:10*l, 7*l:(7+1)*l])
NewMM1[0,8] = np.sum(MM1[0*l:1*l, 8*l:(8+1)*l])
NewMM1[1,8] = np.sum(MM1[1*l:2*l, 8*l:(8+1)*l])
NewMM1[2,8] = np.sum(MM1[2*l:3*l, 8*l:(8+1)*l])
NewMM1[3,8] = np.sum(MM1[3*l:4*l, 8*l:(8+1)*l])
NewMM1[4,8] = np.sum(MM1[4*l:5*l, 8*l:(8+1)*l])
NewMM1[5,8] = np.sum(MM1[5*l:6*l, 8*l:(8+1)*l])
NewMM1[6,8] = np.sum(MM1[6*l:7*l, 8*l:(8+1)*l])
NewMM1[7,8] = np.sum(MM1[7*l:8*l, 8*l:(8+1)*l])
NewMM1[8,8] = np.sum(MM1[8*l:9*l, 8*l:(8+1)*l])
NewMM1[9,8] = np.sum(MM1[9*l:10*l, 8*l:(8+1)*l])
NewMM1[0,9] = np.sum(MM1[0*l:1*l, 9*l:(9+1)*l])
NewMM1[1,9] = np.sum(MM1[1*l:2*l, 9*l:(9+1)*l])
NewMM1[2,9] = np.sum(MM1[2*l:3*l, 9*l:(9+1)*l])
NewMM1[3,9] = np.sum(MM1[3*l:4*l, 9*l:(9+1)*l])
NewMM1[4,9] = np.sum(MM1[4*l:5*l, 9*l:(9+1)*l])
NewMM1[5,9] = np.sum(MM1[5*l:6*l, 9*l:(9+1)*l])
NewMM1[6,9] = np.sum(MM1[6*l:7*l, 9*l:(9+1)*l])
NewMM1[7,9] = np.sum(MM1[7*l:8*l, 9*l:(9+1)*l])
NewMM1[8,9] = np.sum(MM1[8*l:9*l, 9*l:(9+1)*l])
NewMM1[9,9] = np.sum(MM1[9*l:10*l, 9*l:(9+1)*l])

#because it wouldn't work with nested loops.

NewMM2[0,0] = np.sum(MM2[0*l:1*l, 0:(0+1)*l])
NewMM2[1,0] = np.sum(MM2[1*l:2*l, 0:(0+1)*l])
NewMM2[2,0] = np.sum(MM2[2*l:3*l, 0:(0+1)*l])
NewMM2[3,0] = np.sum(MM2[3*l:4*l, 0:(0+1)*l])
NewMM2[4,0] = np.sum(MM2[4*l:5*l, 0:(0+1)*l])
NewMM2[5,0] = np.sum(MM2[5*l:6*l, 0:(0+1)*l])
NewMM2[6,0] = np.sum(MM2[6*l:7*l, 0:(0+1)*l])
NewMM2[7,0] = np.sum(MM2[7*l:8*l, 0:(0+1)*l])
NewMM2[8,0] = np.sum(MM2[8*l:9*l, 0:(0+1)*l])
NewMM2[9,0] = np.sum(MM2[9*l:10*l, 0:(0+1)*l])    
NewMM2[0,1] = np.sum(MM2[0*l:1*l, 1*l:(1+1)*l])
NewMM2[1,1] = np.sum(MM2[1*l:2*l, 1*l:(1+1)*l])
NewMM2[2,1] = np.sum(MM2[2*l:3*l, 1*l:(1+1)*l])
NewMM2[3,1] = np.sum(MM2[3*l:4*l, 1*l:(1+1)*l])
NewMM2[4,1] = np.sum(MM2[4*l:5*l, 1*l:(1+1)*l])
NewMM2[5,1] = np.sum(MM2[5*l:6*l, 1*l:(1+1)*l])
NewMM2[6,1] = np.sum(MM2[6*l:7*l, 1*l:(1+1)*l])
NewMM2[7,1] = np.sum(MM2[7*l:8*l, 1*l:(1+1)*l])
NewMM2[8,1] = np.sum(MM2[8*l:9*l, 1*l:(1+1)*l])
NewMM2[9,1] = np.sum(MM2[9*l:10*l, 1*l:(1+1)*l])
NewMM2[0,2] = np.sum(MM2[0*l:1*l, 2*l:(2+1)*l])
NewMM2[1,2] = np.sum(MM2[1*l:2*l, 2*l:(2+1)*l])
NewMM2[2,2] = np.sum(MM2[2*l:3*l, 2*l:(2+1)*l])
NewMM2[3,2] = np.sum(MM2[3*l:4*l, 2*l:(2+1)*l])
NewMM2[4,2] = np.sum(MM2[4*l:5*l, 2*l:(2+1)*l])
NewMM2[5,2] = np.sum(MM2[5*l:6*l, 2*l:(2+1)*l])
NewMM2[6,2] = np.sum(MM2[6*l:7*l, 2*l:(2+1)*l])
NewMM2[7,2] = np.sum(MM2[7*l:8*l, 2*l:(2+1)*l])
NewMM2[8,2] = np.sum(MM2[8*l:9*l, 2*l:(2+1)*l])
NewMM2[9,2] = np.sum(MM2[9*l:10*l, 2*l:(2+1)*l])
NewMM2[0,3] = np.sum(MM2[0*l:1*l, 3*l:(3+1)*l])
NewMM2[1,3] = np.sum(MM2[1*l:2*l, 3*l:(3+1)*l])
NewMM2[2,3] = np.sum(MM2[2*l:3*l, 3*l:(3+1)*l])
NewMM2[3,3] = np.sum(MM2[3*l:4*l, 3*l:(3+1)*l])
NewMM2[4,3] = np.sum(MM2[4*l:5*l, 3*l:(3+1)*l])
NewMM2[5,3] = np.sum(MM2[5*l:6*l, 3*l:(3+1)*l])
NewMM2[6,3] = np.sum(MM2[6*l:7*l, 3*l:(3+1)*l])
NewMM2[7,3] = np.sum(MM2[7*l:8*l, 3*l:(3+1)*l])
NewMM2[8,3] = np.sum(MM2[8*l:9*l, 3*l:(3+1)*l])
NewMM2[9,3] = np.sum(MM2[9*l:10*l, 3*l:(3+1)*l])
NewMM2[0,4] = np.sum(MM2[0*l:1*l, 4*l:(4+1)*l])
NewMM2[1,4] = np.sum(MM2[1*l:2*l, 4*l:(4+1)*l])
NewMM2[2,4] = np.sum(MM2[2*l:3*l, 4*l:(4+1)*l])
NewMM2[3,4] = np.sum(MM2[3*l:4*l, 4*l:(4+1)*l])
NewMM2[4,4] = np.sum(MM2[4*l:5*l, 4*l:(4+1)*l])
NewMM2[5,4] = np.sum(MM2[5*l:6*l, 4*l:(4+1)*l])
NewMM2[6,4] = np.sum(MM2[6*l:7*l, 4*l:(4+1)*l])
NewMM2[7,4] = np.sum(MM2[7*l:8*l, 4*l:(4+1)*l])
NewMM2[8,4] = np.sum(MM2[8*l:9*l, 4*l:(4+1)*l])
NewMM2[9,4] = np.sum(MM2[9*l:10*l, 4*l:(4+1)*l])
NewMM2[0,5] = np.sum(MM2[0*l:1*l, 5*l:(5+1)*l])
NewMM2[1,5] = np.sum(MM2[1*l:2*l, 5*l:(5+1)*l])
NewMM2[2,5] = np.sum(MM2[2*l:3*l, 5*l:(5+1)*l])
NewMM2[3,5] = np.sum(MM2[3*l:4*l, 5*l:(5+1)*l])
NewMM2[4,5] = np.sum(MM2[4*l:5*l, 5*l:(5+1)*l])
NewMM2[5,5] = np.sum(MM2[5*l:6*l, 5*l:(5+1)*l])
NewMM2[6,5] = np.sum(MM2[6*l:7*l, 5*l:(5+1)*l])
NewMM2[7,5] = np.sum(MM2[7*l:8*l, 5*l:(5+1)*l])
NewMM2[8,5] = np.sum(MM2[8*l:9*l, 5*l:(5+1)*l])
NewMM2[9,5] = np.sum(MM2[9*l:10*l, 5*l:(5+1)*l])
NewMM2[0,6] = np.sum(MM2[0*l:1*l, 6*l:(6+1)*l])
NewMM2[1,6] = np.sum(MM2[1*l:2*l, 6*l:(6+1)*l])
NewMM2[2,6] = np.sum(MM2[2*l:3*l, 6*l:(6+1)*l])
NewMM2[3,6] = np.sum(MM2[3*l:4*l, 6*l:(6+1)*l])
NewMM2[4,6] = np.sum(MM2[4*l:5*l, 6*l:(6+1)*l])
NewMM2[5,6] = np.sum(MM2[5*l:6*l, 6*l:(6+1)*l])
NewMM2[6,6] = np.sum(MM2[6*l:7*l, 6*l:(6+1)*l])
NewMM2[7,6] = np.sum(MM2[7*l:8*l, 6*l:(6+1)*l])
NewMM2[8,6] = np.sum(MM2[8*l:9*l, 6*l:(6+1)*l])
NewMM2[9,6] = np.sum(MM2[9*l:10*l, 6*l:(6+1)*l])
NewMM2[0,7] = np.sum(MM2[0*l:1*l, 7*l:(7+1)*l])
NewMM2[1,7] = np.sum(MM2[1*l:2*l, 7*l:(7+1)*l])
NewMM2[2,7] = np.sum(MM2[2*l:3*l, 7*l:(7+1)*l])
NewMM2[3,7] = np.sum(MM2[3*l:4*l, 7*l:(7+1)*l])
NewMM2[4,7] = np.sum(MM2[4*l:5*l, 7*l:(7+1)*l])
NewMM2[5,7] = np.sum(MM2[5*l:6*l, 7*l:(7+1)*l])
NewMM2[6,7] = np.sum(MM2[6*l:7*l, 7*l:(7+1)*l])
NewMM2[7,7] = np.sum(MM2[7*l:8*l, 7*l:(7+1)*l])
NewMM2[8,7] = np.sum(MM2[8*l:9*l, 7*l:(7+1)*l])
NewMM2[9,7] = np.sum(MM2[9*l:10*l, 7*l:(7+1)*l])
NewMM2[0,8] = np.sum(MM2[0*l:1*l, 8*l:(8+1)*l])
NewMM2[1,8] = np.sum(MM2[1*l:2*l, 8*l:(8+1)*l])
NewMM2[2,8] = np.sum(MM2[2*l:3*l, 8*l:(8+1)*l])
NewMM2[3,8] = np.sum(MM2[3*l:4*l, 8*l:(8+1)*l])
NewMM2[4,8] = np.sum(MM2[4*l:5*l, 8*l:(8+1)*l])
NewMM2[5,8] = np.sum(MM2[5*l:6*l, 8*l:(8+1)*l])
NewMM2[6,8] = np.sum(MM2[6*l:7*l, 8*l:(8+1)*l])
NewMM2[7,8] = np.sum(MM2[7*l:8*l, 8*l:(8+1)*l])
NewMM2[8,8] = np.sum(MM2[8*l:9*l, 8*l:(8+1)*l])
NewMM2[9,8] = np.sum(MM2[9*l:10*l, 8*l:(8+1)*l])
NewMM2[0,9] = np.sum(MM2[0*l:1*l, 9*l:(9+1)*l])
NewMM2[1,9] = np.sum(MM2[1*l:2*l, 9*l:(9+1)*l])
NewMM2[2,9] = np.sum(MM2[2*l:3*l, 9*l:(9+1)*l])
NewMM2[3,9] = np.sum(MM2[3*l:4*l, 9*l:(9+1)*l])
NewMM2[4,9] = np.sum(MM2[4*l:5*l, 9*l:(9+1)*l])
NewMM2[5,9] = np.sum(MM2[5*l:6*l, 9*l:(9+1)*l])
NewMM2[6,9] = np.sum(MM2[6*l:7*l, 9*l:(9+1)*l])
NewMM2[7,9] = np.sum(MM2[7*l:8*l, 9*l:(9+1)*l])
NewMM2[8,9] = np.sum(MM2[8*l:9*l, 9*l:(9+1)*l])
NewMM2[9,9] = np.sum(MM2[9*l:10*l, 9*l:(9+1)*l])

Now I will create two 10x10 matrices that have the condensed information of the 8300x8300 matrices.

In [10]:
NewMM1

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    2,    2,    3,    2,    0,    0,    0,    0],
       [   0,    0,    4,   20,   60,   64,    3,    0,    0,    0],
       [   0,    0,    7,   26,  574, 1019,   10,    1,    0,    0],
       [   0,    0,    6,   29,  621, 2750,  122,    8,    0,    0],
       [   0,    0,    1,    2,   16,  126,   49,    1,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    1,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0]])

In [11]:
NewMM2

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    2,    1,    2,    4,    0,    0,    0,    0],
       [   0,    0,    3,   26,   42,   55,    2,    1,    0,    0],
       [   0,    0,    3,   28,  440,  659,   10,    2,    0,    0],
       [   0,    0,    9,   36,  404, 1842,   72,    8,    2,    0],
       [   0,    0,    0,    2,   16,  101,   43,    1,    0,    0],
       [   0,    0,    0,    0,    0,    1,    0,    1,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0]])

In [50]:
def Reward_Matrix1(n):
    RewardMatrix1=np.zeros((n,n))
    for ii in range(n):
            for jj in range(n):
                RewardMatrix1[ii,jj]=normalvariate(31.0,9.0)
    return RewardMatrix1

In [51]:
def Reward_Matrix2(n):
    RewardMatrix2=np.zeros((n,n))
    for ii in range(n):
            for jj in range(n):
                RewardMatrix2[ii,jj]=normalvariate(30.0,5.0)
    return RewardMatrix2

In [52]:
#Creating the reward matrices.
R1=Reward_Matrix1(10)
R2=Reward_Matrix2(10)

In [53]:
#Creating the initial policy vector.
p0 = np.array([1,1,1,1,1,1,1,1,1,1])

In [54]:
NewMM1.shape[0]

10

In [55]:
#This is the process to transform the Mean Matrix in the Transition Matrix

MMM1 = NewMM1.copy()
MMM1

T1 = np.zeros((10,10), dtype=float)

for ii in range (0,10):
    sf1 = np.sum(MMM1[ii,:])
    if sf1 != 0:
        T1[ii,:] = MMM1[ii,:]/(np.sum(MMM1[ii,:]))
    else:
        T1[ii,:] = 1/10
T1

array([[1.00000000e-01, 1.00000000e-01, 1.00000000e-01, 1.00000000e-01,
        1.00000000e-01, 1.00000000e-01, 1.00000000e-01, 1.00000000e-01,
        1.00000000e-01, 1.00000000e-01],
       [1.00000000e-01, 1.00000000e-01, 1.00000000e-01, 1.00000000e-01,
        1.00000000e-01, 1.00000000e-01, 1.00000000e-01, 1.00000000e-01,
        1.00000000e-01, 1.00000000e-01],
       [0.00000000e+00, 0.00000000e+00, 2.22222222e-01, 2.22222222e-01,
        3.33333333e-01, 2.22222222e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.64900662e-02, 1.32450331e-01,
        3.97350993e-01, 4.23841060e-01, 1.98675497e-02, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 4.27611484e-03, 1.58827123e-02,
        3.50641417e-01, 6.22480147e-01, 6.10873549e-03, 6.10873549e-04,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.69683258e-03, 8.20135747e-03,
   

In [56]:
#This is the process to transform the Mean Matrix in the Transition Matrix

MMM2 = NewMM2.copy()
MMM2

T2 = np.zeros((10,10), dtype=float)

for ii in range (0,10):
    sf2 = np.sum(MMM2[ii,:])
    if sf2 != 0:
        T2[ii,:] = MMM2[ii,:]/(np.sum(MMM2[ii,:]))
    else:
        T2[ii,:] = 1/10
T2

array([[0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
        0.1       , 0.1       , 0.1       , 0.1       , 0.1       ],
       [0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
        0.1       , 0.1       , 0.1       , 0.1       , 0.1       ],
       [0.        , 0.        , 0.22222222, 0.11111111, 0.22222222,
        0.44444444, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.02325581, 0.20155039, 0.3255814 ,
        0.42635659, 0.01550388, 0.00775194, 0.        , 0.        ],
       [0.        , 0.        , 0.00262697, 0.02451839, 0.38528897,
        0.57705779, 0.00875657, 0.00175131, 0.        , 0.        ],
       [0.        , 0.        , 0.00379267, 0.01517067, 0.17024863,
        0.77623262, 0.03034134, 0.00337126, 0.00084282, 0.        ],
       [0.        , 0.        , 0.        , 0.01226994, 0.09815951,
        0.6196319 , 0.26380368, 0.00613497, 0.        , 0.        ],
       [0.        , 0.        , 0.       

In [57]:
T = np.array([T1,T2])
T.shape

(2, 10, 10)

In [58]:
R = np.array([R1,R2])
R.shape

(2, 10, 10)

In [59]:
pi = mdptoolbox.mdp.PolicyIteration(T, R, 0.1, policy0=p0)

In [60]:
pi.run()

In [61]:
pi.policy

(1, 0, 0, 1, 0, 1, 1, 1, 0, 1)

In [62]:
pi.V

(34.87967086268432,
 36.266310752296995,
 37.81416133786079,
 39.722429009753526,
 41.292264080118954,
 44.03414148657187,
 30.31138683185166,
 41.11525797830183,
 37.075000433036934,
 34.47614944211456)

In [63]:
pi.time

0.004553079605102539