In [1]:
import numpy as np
from random import*

In [2]:
#takes place the generation of a matrix. In particular, a NxN matrix, full of ones.
#N=randrange(randint(10,100))
N=4
#M=4
MA=np.ones((N,N))

In [3]:
#print it
print(MA)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
#Its shape
MA.shape

(4, 4)

In [5]:
#filling it with random numbers.
for ii in range(N):
    for jj in range(N):
        MA[ii,jj]=random()
print(MA)

[[0.79676701 0.70721337 0.47840546 0.72699573]
 [0.14411764 0.4786106  0.43416338 0.55419151]
 [0.46959663 0.75803494 0.12284698 0.57867024]
 [0.29576703 0.91204138 0.83510876 0.32329858]]


In [8]:
#determining the sum of the entries of the row. --I think it should be rows--. 
#then, divide each entry of a column by the sum; normalizing.
for ii in range(N):
    sf1=np.sum(MA[ii,:])
    MA[ii,:]=MA[ii,:]/sf1
print(MA)

[[0.29407707 0.26102391 0.17657368 0.26832534]
 [0.08945388 0.29707381 0.2694854  0.34398691]
 [0.24342168 0.39293752 0.06367937 0.29996143]
 [0.1249958  0.38544303 0.3529301  0.13663107]]


In [9]:
#checking that the sum of a column is
np.sum(MA,axis=1)

array([1., 1., 1., 1.])

In [10]:
#finding eigenvalues and eigenstates.
np.linalg.eig(MA)

(array([ 1.        +0.j        ,  0.15226828+0.j        ,
        -0.18040348+0.03456711j, -0.18040348-0.03456711j]),
 array([[-0.5       +0.j        ,  0.89211243+0.j        ,
         -0.14332173-0.01354746j, -0.14332173+0.01354746j],
        [-0.5       +0.j        , -0.40647962+0.j        ,
         -0.41266274-0.19343971j, -0.41266274+0.19343971j],
        [-0.5       +0.j        ,  0.12107001+0.j        ,
         -0.21619193+0.29430307j, -0.21619193-0.29430307j],
        [-0.5       +0.j        , -0.15572984+0.j        ,
          0.79888212+0.j        ,  0.79888212-0.j        ]]))

In [11]:
#Making the matrix a 1D array
VecMA = np.asarray(MA).reshape(-1)
print(VecMA)

[0.29407707 0.26102391 0.17657368 0.26832534 0.08945388 0.29707381
 0.2694854  0.34398691 0.24342168 0.39293752 0.06367937 0.29996143
 0.1249958  0.38544303 0.3529301  0.13663107]


In [104]:
#import csv
#with open('Medallion_2011_specifc_time_dataset.csv') as csvfile:
#     reader = csv.DictReader(csvfile)
#     for col in reader:
#         print(col['Zones'])

In [12]:
#pandas is simpler than numpy.
import pandas as pd

In [13]:
#creating a DataFrame --pandas matrix, if you want-- with a command. no header means to use every values as data, not as names. 

#m = pd.read_csv('Medallion_2011_specifc_time_dataset.csv', header=None)
m1 = pd.read_csv('Demand_Jun_04_2011.csv', header=None)
m2 = pd.read_csv('Demand_Jun_05_2011.csv', header=None)
m3 = pd.read_csv('Demand_Jun_06_2011.csv', header=None)
m4 = pd.read_csv('Demand_Jun_07_2011.csv', header=None)
m5 = pd.read_csv('Demand_Jun_08_2011.csv', header=None)


D:\Programas\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [14]:
#Crating a matrix (numpy array) with the values of the mi (i=1,2,3,4,5) pandas files.

#MT = m.values
MT1 = m1.values
MT2 = m2.values
MT3 = m3.values
MT4 = m4.values
MT5 = m5.values

In [15]:
#Checking the size of the arrays.

#print(MT.shape)
print(MT1.shape)
print(MT2.shape)
print(MT3.shape)
print(MT4.shape)
print(MT5.shape)

(8301, 8301)
(8301, 8301)
(8301, 8301)
(8301, 8301)
(8301, 8301)


In [16]:
#Checkin that the first column and row are the headers.

#print(MT[:,0])
#print(MT[0,:])

print(MT1[:,0])
print(MT1[0,:])

print(MT2[:,0])
print(MT2[0,:])

print(MT3[:,0])
print(MT3[0,:])

print(MT4[:,0])
print(MT4[0,:])

print(MT5[:,0])
print(MT5[0,:])

['PZone' '309269' '309270' ... 391366 391367 391368]
['PZone' 309269 309270 ... 391366 391367 391368]
['PZone' '309269' '309270' ... 391366 391367 391368]
['PZone' 309269 309270 ... 391366 391367 391368]
['PZone' '309269' '309270' ... 391366 391367 391368]
['PZone' 309269 309270 ... 391366 391367 391368]
['PZone' '309269' '309270' ... 391366 391367 391368]
['PZone' 309269 309270 ... 391366 391367 391368]
['PZone' '309269' '309270' ... 391366 391367 391368]
['PZone' 309269 309270 ... 391366 391367 391368]


In [17]:
#Deleting the headers.

#Mm = np.delete(MT,0,1)
#Mm = np.delete(Mm,0,0)

M1 = np.delete(MT1,0,1)
M1 = np.delete(M1,0,0)

M2 = np.delete(MT2,0,1)
M2 = np.delete(M2,0,0)

M3 = np.delete(MT3,0,1)
M3 = np.delete(M3,0,0)

M4 = np.delete(MT4,0,1)
M4 = np.delete(M4,0,0)

M5 = np.delete(MT5,0,1)
M5 = np.delete(M5,0,0)

In [18]:
#Checking the size

#print(Mm.shape)
print(M1.shape)
print(M2.shape)
print(M3.shape)
print(M4.shape)
print(M5.shape)

(8300, 8300)
(8300, 8300)
(8300, 8300)
(8300, 8300)
(8300, 8300)


In [19]:
#Adding the matrices, elementwise.

suma1=np.add(M1, M2)
suma2=np.add(suma1,M3)
suma3=np.add(suma2,M4)
preMint=np.add(suma3,M5)
print(preMint.shape)

(8300, 8300)


In [20]:
preMfloat=preMint.astype(float)

In [21]:
type(preMfloat[4,7])

numpy.float64

In [22]:
#see M
preMfloat

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [23]:
#determining the sum of the entries of the column --I think it should be rows--. 
#then, divide each entry of a column by the sum; normalizing.

preM=preMfloat.copy()                       #creates a copy of MT.
#case="0"                       #chooses the way of changing 0.0.
lsf=[]                             #creates a list of the row sums "list suma fila".
lzeros=[]                          #creates a list of zeros.

for ii in range(0,8300): 
    sf=np.sum(preM[ii,:])            #the values of the sum of the elements each row.
    lsf.append(sf)                 #filling the lsf list with its values.
    sumlsf=sum(lsf)                #this is the sum of the entries of lsf. 
    if sf!=0.0:                      #if sf is different from 0,
        preM[ii,:]=preM[ii,:]/sf       #divide each value of the row by the sum of the elements of the row. Normalizing.
    else:
#        lzeros.append(ii)          #otherwise, fill the lzeros list with something, in this case, ii.
        preM[ii,:]=1.0/8300
print(preM)
print(type(preM))

#if case=="0":                      #to change 0.0 with 0.0. Actually, does nothing.
#    pass
#    print(MN)

#elif case=="1/n":                  #to change 0.0 with a fraction of unit. It is a mean that adds up to 1.
#    for ii in lzeros:
#        MN[ii,:]=1.0/8300
#    print(MN)
    
#elif case=="mean1":             
#    entries=len(lsf)-len(lzeros)   #quantity of non-zero-sum columns. lenght of lsf (equal to the number of rows) minus lenght of the list of rows with zero sum.
#    for ii in lzeros:
#        MN[ii,:]=sumlsf/entries
#        MN[ii,:]=MN[ii,:]/np.sum(MN[ii,:])
#    print(MN)
    
#elif case=="mean2":
#    for ii in lzeros:
#        MN[ii,:]=sumlsf/len(lsf)
#        MN[ii,:]=MN[ii,:]/np.sum(MN[ii,:])
#    print(MN)


[[0.00012048 0.00012048 0.00012048 ... 0.00012048 0.00012048 0.00012048]
 [0.00012048 0.00012048 0.00012048 ... 0.00012048 0.00012048 0.00012048]
 [0.00012048 0.00012048 0.00012048 ... 0.00012048 0.00012048 0.00012048]
 ...
 [0.00012048 0.00012048 0.00012048 ... 0.00012048 0.00012048 0.00012048]
 [0.00012048 0.00012048 0.00012048 ... 0.00012048 0.00012048 0.00012048]
 [0.00012048 0.00012048 0.00012048 ... 0.00012048 0.00012048 0.00012048]]
<class 'numpy.ndarray'>


In [24]:
A = np.asmatrix(preM)

In [25]:
unapcked = preM.ravel()
#unapcked = np.matrix.ravel(A)
#unpacked = np.asarray(unapcked)
print(type(unapcked))
print(unapcked)

<class 'numpy.ndarray'>
[0.00012048 0.00012048 0.00012048 ... 0.00012048 0.00012048 0.00012048]


In [26]:
#checking for NaNs

for i, elemnt in enumerate(unapcked):
    
    if elemnt != elemnt:
        
        print(i)

In [27]:
np.sum(A,axis=1)

matrix([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]])

In [28]:
#Creating the csv file of the transition matrix.
np.savetxt('transition.csv', A, delimiter=',')

In [29]:
#Creating a file with the values of the sum of the rows of A. To eye-check.
sumrows=np.sum(A,axis=1)
np.savetxt('sumrows.csv', sumrows, delimiter=',')

In [78]:
#finding eigenvalues and eigenstates.
np.linalg.eig(A)

(array([0.99768504+0.j, 0.94327584+0.j, 0.74991261+0.j, ...,
        1.        +0.j, 1.        +0.j, 1.        +0.j]),
 matrix([[ 0.01098103+0.j, -0.0111715 +0.j, -0.00097839+0.j, ...,
           0.0093138 +0.j,  0.0093138 +0.j,  0.01010558+0.j],
         [ 0.01098103+0.j, -0.0111715 +0.j, -0.00097839+0.j, ...,
           0.0093138 +0.j,  0.0093138 +0.j,  0.01010558+0.j],
         [ 0.01098103+0.j, -0.0111715 +0.j, -0.00097839+0.j, ...,
           0.0093138 +0.j,  0.0093138 +0.j,  0.01010558+0.j],
         ...,
         [ 0.01098103+0.j, -0.0111715 +0.j, -0.00097839+0.j, ...,
           0.0093138 +0.j,  0.0093138 +0.j,  0.01010558+0.j],
         [ 0.01098103+0.j, -0.0111715 +0.j, -0.00097839+0.j, ...,
           0.0093138 +0.j,  0.0093138 +0.j,  0.01010558+0.j],
         [ 0.01098103+0.j, -0.0111715 +0.j, -0.00097839+0.j, ...,
           0.0093138 +0.j,  0.0093138 +0.j,  0.01010558+0.j]]))

In [1]:
from scipy import linalg as LN

In [80]:
LN.eig(A)

(array([0.99768504+0.j, 0.94327584+0.j, 0.74991261+0.j, ...,
        1.        +0.j, 1.        +0.j, 1.        +0.j]),
 array([[ 0.01098103+0.j, -0.0111715 +0.j, -0.00097839+0.j, ...,
          0.0093138 +0.j,  0.0093138 +0.j,  0.01010558+0.j],
        [ 0.01098103+0.j, -0.0111715 +0.j, -0.00097839+0.j, ...,
          0.0093138 +0.j,  0.0093138 +0.j,  0.01010558+0.j],
        [ 0.01098103+0.j, -0.0111715 +0.j, -0.00097839+0.j, ...,
          0.0093138 +0.j,  0.0093138 +0.j,  0.01010558+0.j],
        ...,
        [ 0.01098103+0.j, -0.0111715 +0.j, -0.00097839+0.j, ...,
          0.0093138 +0.j,  0.0093138 +0.j,  0.01010558+0.j],
        [ 0.01098103+0.j, -0.0111715 +0.j, -0.00097839+0.j, ...,
          0.0093138 +0.j,  0.0093138 +0.j,  0.01010558+0.j],
        [ 0.01098103+0.j, -0.0111715 +0.j, -0.00097839+0.j, ...,
          0.0093138 +0.j,  0.0093138 +0.j,  0.01010558+0.j]]))

In [30]:
eigvals = np.linalg.eigvals(A)

In [31]:
np.savetxt('eigvals.csv', eigvals, delimiter=',')